import {
	type AgentToolResult,
	defineTool,
	type ToolDefinition,
} from "@earendil-works/pi-coding-agent"
import { type Static, Type } from "typebox"
import type { EventBus } from "../events"
import type { Store } from "../store"
import type { Mission, RoleIdentity } from "../types"

// ---------------------------------------------------------------------------
// define_mission (mission_lead only).
//
// The agent supplies the mission's human-authored content; the immutable `id`
// comes from the RoleIdentity closure (pre-generated by the Orchestrator at
// mission start — ticket 06 D2) and `repoPath` is supplied by the Orchestrator
// (Model C: one Orchestrator, many missions across many repos). Status
// defaults to `in_progress`.
// ---------------------------------------------------------------------------

export const DefineMissionInputSchema = Type.Object({
	title: Type.String({
		description:
			"A short, human-readable mission title (a label, not a sentence). " +
			"Aim for <= 50 characters, like a git commit subject line.",
	}),
	description: Type.String(),
	acceptanceCriteria: Type.Array(Type.String()),
})
export type DefineMissionInput = Static<typeof DefineMissionInputSchema>

export function createDefineMissionTool(
	store: Store,
	bus: EventBus,
	who: RoleIdentity,
	repoPath: string,
): ToolDefinition<typeof DefineMissionInputSchema> {
	return defineTool<typeof DefineMissionInputSchema>({
		name: "define_mission",
		label: "Define Mission",
		description:
			"Define the mission: extract its objectives, acceptance criteria, and " +
			"constraints into a structured definition. The mission id is assigned " +
			"automatically.",
		parameters: DefineMissionInputSchema,
		execute: async (
			_toolCallId: string,
			params: DefineMissionInput,
		): Promise<AgentToolResult<{ mission: Mission }>> => {
			const mission: Mission = {
				id: who.missionId,
				repoPath,
				title: params.title,
				description: params.description,
				acceptanceCriteria: params.acceptanceCriteria,
				status: "in_progress",
			}
			await store.writeMission(mission)
			bus.emit({
				type: "mission-defined",
				missionId: who.missionId,
				mission,
			})
			return {
				content: [
					{
						type: "text",
						text: `Mission defined: ${mission.title} (id ${mission.id}).`,
					},
				],
				details: { mission },
			}
		},
	})
}
